# **************************************************************************
# *
# * Authors:   Blanca Pueche (blanca.pueche@cnb.csis.es)
# *
# * Unidad de  Bioinformatica of Centro Nacional de Biotecnologia , CSIC
# *
# * This program is free software; you can redistribute it and/or modify
# * it under the terms of the GNU General Public License as published by
# * the Free Software Foundation; either version 2 of the License, or
# * (at your option) any later version.
# *
# * This program is distributed in the hope that it will be useful,
# * but WITHOUT ANY WARRANTY; without even the implied warranty of
# * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# * GNU General Public License for more details.
# *
# * You should have received a copy of the GNU General Public License
# * along with this program; if not, write to the Free Software
# * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA
# * 02111-1307  USA
# *
# *  All comments concerning this program package may be sent to the
# *  e-mail address 'scipion@cnb.csic.es'
# *
# **************************************************************************
import json

import os
import re
import string

import pyworkflow.protocol.params as params
from pwem.protocols import EMProtocol
from pyworkflow.object import String

from pwchem import Plugin
from biofold.constants import PROTENIX_DIC

from pwem.objects import  AtomStruct, SetOfAtomStructs
from pwchem.utils.utilsFasta import parseFasta
from .protocol_chai import ProtChai


class ProtProtenix(EMProtocol):
    """
    Protocol to use Protenix model.

    AI Generated:

        ProtProtenix - User Manual

        Overview
        --------
        This protocol performs protein (and nucleic acid) structure prediction
        using the Protenix deep learning framework. It supports input sequences
        from multiple sources (Scipion Sequence objects, AtomStruct-derived sequences,
        or FASTA files) and generates multiple structural models with associated
        confidence scores.

        Inputs
        ------
        - **inputOrigin**: Defines the source of sequences:
            - Sequence object
            - AtomStruct (structure-derived sequence)
            - FASTA file
        - **inputSequence / inputAtomStruct / file**: Selected input depending on origin.
        - **inputList**: List of sequences to include in the prediction job.
        - **entityType**: Type of biological sequence (Protein, DNA, RNA).
        - **msa**: Whether to use Multiple Sequence Alignments for improved predictions.
        - **sample**: Number of output models to generate.
        - **steps**: Number of sampling steps during prediction.
        - **model**: Protenix model version to use.

        Workflow
        --------
        1. **Input preparation**:
           - Parses sequences from selected input source.
           - Supports multiple sequences combined into a single prediction job.
           - Automatically assigns chain identifiers (A, B, C, ...).

        2. **Sequence processing**:
           - Cleans sequences and replaces unsupported residues (e.g., 'X').
           - Infers entity type (protein, DNA, RNA) if not explicitly defined.
           - Converts sequences into Protenix-compatible JSON format.

        3. **Protenix execution**:
           - Runs the Protenix model using the generated input JSON.
           - Supports GPU acceleration and configurable sampling parameters.
           - Generates multiple structural models (CIF files).

        4. **Score extraction**:
           - Parses confidence JSON files generated by Protenix.
           - Extracts ranking scores for each predicted model.
           - Identifies the best-scoring model.

        5. **Output generation**:
           - Collects all predicted structures into a SetOfAtomStructs.
           - Assigns confidence scores to each structure.
           - Selects and outputs the best model separately.

        Outputs
        -------
        - **outputBestAtomStruct**: The highest-ranked predicted structure.
        - **outputSetOfAtomStructs**: Set of all generated models with scores.
        - **protenix_scores.txt**: Summary file with ranking scores.

        Practical Recommendations
        -------------------------
        - Use MSAs for better prediction accuracy when computational resources allow.
        - For benchmarking, use models aligned with earlier datasets.
        - For best performance, use the latest available model version.

        Summary & Interpretation
        ------------------------
        - Each generated model has a **ranking score** indicating prediction confidence.
        - Higher scores correspond to more reliable structures.
        - The best model is automatically selected based on this score.

        Warnings
        --------
        - Invalid or malformed sequences may cause failures or degraded predictions.
        - Unknown residues ('X') are replaced automatically, which may affect accuracy.
        - Large inputs or high sampling parameters may require significant GPU resources.
        - Ensure Protenix environment and dependencies are correctly configured.
    """
    _label = 'protenix modelling'
    models = ['protenix-v2','protenix_base_default_v1.0.0', 'protenix_base_20250630_v1.0.0', 'protenix_base_default_v0.5.0']

    # -------------------------- DEFINE param functions ----------------------
    def _defineParams(self, form):
        """ Define the input parameters that will be used.
        Params:
            form: this is the form to be populated with sections and params.
        """
        form.addHidden('useGpu', params.BooleanParam, default=True,
                       label="Use GPU for execution",
                       help="This protocol has both CPU and GPU implementation. Choose one.")

        form.addHidden('gpuList', params.StringParam, default='0',
                       label="Choose GPU IDs",
                       help="Comma-separated GPU devices that can be used.")

        form.addSection(label='Input')
        form.addParam('inputOrigin', params.EnumParam, default=0,
                      label='Input origin: ', choices=['Sequence', 'SetOfSequences', 'AtomStruct', 'fasta file'],
                      help='Input origin to add to the set')
        ProtChai._addInputForm(form)

        form.addParam('inputList', params.TextParam, width=100, condition='inputOrigin!=3',
                      default='', label='List of inputs: ',
                      help='The list of input to use for the final output set.')

        form.addParam('file', params.FileParam, condition='inputOrigin == 3',
                      label='Sequence file: ',
                      help='Select the fasta file.')

        group = form.addGroup('Parameters')
        group.addParam('msa', params.BooleanParam, default=True,
                      label="Run with MSAs: ",
                      help='Choose whether to run with MSAs for improved performance.')
        group.addParam('sample', params.IntParam, default=5,
                       label='Output models: ', help="Number of output models for prediction.")
        group.addParam('steps', params.IntParam, default=200,
                        label='Sampling steps: ', help="Number of sampling steps for prediction.")
        group.addParam('model', params.EnumParam, default=0, choices=self.models,
                        label='Model: ', help="Model options:\n\n- protenix_base_default_v1.0.0: Default model trained with a data cutoff aligned with AlphaFold3 (2021-09-30). "
                                              "Recommended for fair benchmarking and comparison with other state-of-the-art methods.\n\n- "
                                              "protenix_base_20250630_v1.0.0: Updated model trained with a more recent data cutoff (2025-06-30). "
                                              "Recommended for practical applications and best performance.\n\n- protenix_base_default_v0.5.0: Previous model version. "
                                              "Maintained for backward compatibility with older workflows.")

        form.addParallelSection(threads=4, mpi=1)

    # --------------------------- STEPS functions ------------------------------
    def _insertAllSteps(self):
        if self.inputOrigin.get() == 3:
            self._insertFunctionStep(self.createProtenixJsonFromFastaStep)
        else:
            self._insertFunctionStep(self.createProtenixInputFileStep)

        self._insertFunctionStep(self.runProtenixStep)
        self._insertFunctionStep(self.extractScoreStep)
        self._insertFunctionStep(self.createOutputStep)

    def createProtenixJsonFromFastaStep(self):
        fastaPath = os.path.abspath(self.file.get())
        seqDic = parseFasta(fastaPath)

        chainIdIter = iter(string.ascii_uppercase)
        sequences = []

        for _, sequence in seqDic.items():
            chainId = next(chainIdIter)

            entityType = self.guessEntityType(sequence)

            sequences.append(
                self._buildProtenixEntity(entityType, sequence, chainId)
            )

        jsonPath = os.path.abspath(self._getPath("protenix_input.json"))

        with open(jsonPath, "w") as f:
            json.dump([
                {
                    "name": "protenix_job",
                    "sequences": sequences
                }
            ], f, indent=2)

    def createProtenixInputFileStep(self):
        chainIdIter = iter(string.ascii_uppercase)
        sequences = []

        for inputLine in self.inputList.get().split('\n'):
            if not inputLine.strip():
                continue

            try:
                inpJson = json.loads(inputLine.split(')')[1].strip())
                seqDic = parseFasta(os.path.abspath(inpJson['seqFile']))
                _, sequence = next(iter(seqDic.items()))

                entityType = inpJson.get('entity', None)
                chainId = next(chainIdIter)

                sequences.append(
                    self._buildProtenixEntity(entityType, sequence, chainId)
                )
            except Exception as e:
                print(f"Error parsing input line: {e}")

        self._writeJson(sequences)

    def runProtenixStep(self):
        jsonPath = os.path.abspath(self._getPath("protenix_input.json"))
        args = ['-i', str(jsonPath)]

        args.append(f'-o {os.path.join(os.path.abspath(self._getPath()), "protenix_results")}')

        if self.msa.get():
            args.append("--use_msa TRUE")
        else:
            args.append("--use_msa FALSE")

        args.append(f" --sample {self.sample.get()}")
        args.append(f" --step {self.steps.get()}")
        args.append(f" --model_name {self.getEnumText('model')}")
        args.append(f" --nhmmer_n_cpu {self.numberOfThreads.get()}")

        program_prefix = (
            "export CUDA_HOME=$CONDA_PREFIX && "
            "export CPATH=$CONDA_PREFIX/targets/x86_64-linux/include:$CPATH && "
            "export LD_LIBRARY_PATH=$CONDA_PREFIX/targets/x86_64-linux/lib:$LD_LIBRARY_PATH && "
            f"export PROTENIX_ROOT_DIR={Plugin.getVar(PROTENIX_DIC['home'])} && "
        )

        if self.useGpu.get():
            program_prefix += f"export CUDA_VISIBLE_DEVICES={self.gpuList.get()} && "

        program_prefix += "protenix pred"

        Plugin.runCondaCommand(
            self,
            args=" ".join(args),
            condaDic=PROTENIX_DIC,
            program=program_prefix,
            cwd=os.path.abspath(Plugin.getVar(PROTENIX_DIC['home']))
        )

    def extractScoreStep(self):
        """Extract ranking scores from the confidence JSON files"""
        self.meanScore = {}
        resultsPath = os.path.join(self._getPath(), "protenix_results")

        for root, _, files in os.walk(resultsPath):
            for name in files:
                if "summary_confidence_sample_" in name and name.endswith(".json"):
                    sampleIdx = name.split('_')[-1].split('.')[0]
                    jsonPath = os.path.join(root, name)

                    with open(jsonPath, 'r') as f:
                        data = json.load(f)
                        score = data.get("ranking_score", 0.0)

                    modelName = f"protenix_job_sample_{sampleIdx}"
                    self.meanScore[modelName] = score

        self.bestModel = max(self.meanScore, key=self.meanScore.get)

        scoreFile = self._getExtraPath("protenix_scores.txt")
        with open(scoreFile, "w") as f:
            f.write(f"Best Model: {self.bestModel}\n")
            f.write("-" * 30 + "\n")
            for model, score in sorted(self.meanScore.items()):
                f.write(f"{model}: {score:.4f}\n")

    def createOutputStep(self):
        extraFiles = self.getExtraFiles()  # This now searches recursively
        outputSet = SetOfAtomStructs.create(self._getPath())

        bestSrc = None

        for cifPath in extraFiles:
            modelName = os.path.splitext(os.path.basename(cifPath))[0]

            atomStruct = AtomStruct(filename=cifPath)
            atomStruct.origin = String('Protenix')
            # Set the score we found in the previous step
            score = self.meanScore.get(modelName, 0.0)
            atomStruct.setAttributeValue('score', score)

            outputSet.append(atomStruct)

            if modelName == self.bestModel:
                bestSrc = cifPath

        if bestSrc is None:
            raise Exception(f"Best model {self.bestModel} not found among CIF files.")

        bestStruct = AtomStruct(filename=bestSrc)
        bestStruct.origin = String('Protenix')

        self._defineOutputs(
            outputBestAtomStruct=bestStruct,
            outputSetOfAtomStructs=outputSet
        )

    # --------------------------- INFO functions -----------------------------------
    def _summary(self):
        summary = []
        scoreFile = self._getExtraPath("protenix_scores.txt")

        if os.path.exists(scoreFile):
            with open(scoreFile, "r") as f:
                lines = f.readlines()
                for line in lines:
                    summary.append(line.strip())

        return summary

    def _methods(self):
        methods = []
        return methods

    def _validate(self):
        validations = []
        return validations

    def _warnings(self):
        warnings = []
        return warnings

    # --------------------------- UTILS functions -----------------------------------
    def getExtraFiles(self):
        """Recursively find all .cif files in the protenix_results folder"""
        extraFiles = []
        resultsPath = os.path.join(self._getPath(), "protenix_results")

        if not os.path.exists(resultsPath):
            raise Exception(f"Results path does not exist: {resultsPath}")

        for root, _, files in os.walk(resultsPath):
            for name in files:
                # We only want the sample models, not other metadata CIFs
                if name.lower().endswith(".cif") and "_sample_" in name:
                    extraFiles.append(os.path.join(root, name))

        if not extraFiles:
            raise Exception("No model CIF files found in protenix_results.")

        return extraFiles

    def guessEntityType(self, sequence):
        """ Guess if a sequence is DNA, RNA or Protein """
        sequence = sequence.upper().strip()

        protein_only = re.compile(r'[DEFHIKLMPQRVWY]')

        if protein_only.search(sequence):
            return 'protein'

        if 'U' in sequence:
            return 'rna'

        return 'dna'

    def _buildProtenixEntity(self, entityType, sequence, chainId):
        sequence = "".join(sequence.split()).upper()

        entityType = entityType.lower()

        inner_data = {
            "sequence": sequence,
            "count": 1,
            "id": [str(chainId)]
        }

        # 3. Use the specific Protenix keys
        if entityType == "protein":
            return {"proteinChain": inner_data}
        elif entityType == "dna":
            return {"dnaSequence": inner_data}
        elif entityType == "rna":
            return {"rnaSequence": inner_data}
        else:
            return {"proteinChain": inner_data}

    def _writeJson(self, sequences):
        """ Helper to write the final JSON list structure with correct indentation """
        jsonPath = os.path.abspath(self._getPath("protenix_input.json"))

        # The top level must be a list []
        job_data = [
            {
                "name": "protenix_job",
                "sequences": sequences
            }
        ]

        with open(jsonPath, "w") as f:
            json.dump(job_data, f, indent=2)

    def createProtenixJsonFromFastaStep(self):
        fastaPath = os.path.abspath(self.file.get())
        seqDic = parseFasta(fastaPath)

        chainIdIter = iter(string.ascii_uppercase)
        sequences = []

        for _, sequence in seqDic.items():
            chainId = next(chainIdIter)
            entityType = self.guessEntityType(sequence)
            sequences.append(
                self._buildProtenixEntity(entityType, sequence, chainId)
            )

        self._writeJson(sequences)

    def ensureFastaHasNames(self):
        fastaPath = os.path.abspath(self.file.get())
        outputPath = os.path.join(self._getPath('input.fasta'))

        with open(fastaPath) as f:
            lines = f.readlines()

        fixedLines = []
        counter = 1
        sequenceBuffer = ""
        currentHeader = None


        for line in lines:
            line = line.rstrip("\n")
            if line.startswith(">"):
                if currentHeader is not None:
                    entityType = self.guessEntityType(sequenceBuffer)
                    self.writeSequence(entityType, currentHeader, sequenceBuffer, counter, fixedLines)
                    counter += 1

                header = line[1:]
                if "|name=" in header:
                    header = header.split("|name=")[-1]
                currentHeader = header
                sequenceBuffer = ""
            else:
                sequenceBuffer += line.strip()

        if currentHeader is not None:
            entityType = self.guessEntityType(sequenceBuffer)
            self.writeSequence(entityType, currentHeader, sequenceBuffer, counter, fixedLines)
            counter += 1

        with open(outputPath, 'w') as f:
            f.writelines(fixedLines)

        self.NEWFILE = True

    def writeSequence(self, entityType, header, sequence, counter, fixedLines):
        if not header:
            header = f"seq{counter}"
        fixedLines.append(f">{entityType}|{header}\n")
        for i in range(0, len(sequence), 80):
            fixedLines.append(sequence[i:i + 80] + "\n")

